### ISSUE TITLE
2BUG Terror Strike on 6fi weapon runeword

### ISSUE THREAD

**Issue by terrorbugs** [Median-XL/Issue-Tracker#21] opened 2020-07-04 20:09 UTC
1st bug: not always proc at 1st hit 3-6 if luck
2st bug: grim presece off after 7-15 sec after buff this skill
please fix terror strike before patch 1.6. this very cool hiden mechanic old paladin ty.

**Comment by terrorbugs** [comment] 2020-07-04 20:14
P.S. this mechanic only use with swap weapons like buff from shamanka, i use this on unholy melee paladin to kill uldy tell me if it not bug.

**Comment by terrorbugs** [comment] 2020-07-04 20:39
video with bugs https://www.youtube.com/watch?v=t97nEEhQJOE

**Comment by GavinK88** [comment] 2020-07-07 22:10
Issues already addressed by SB (i.e. 2nd not a bug)

**Closed by GavinK88** 2020-07-07 22:10 UTC
